### ISSUE TITLE
Syntax error playbook ce_command 

### ISSUE THREAD

**Issue by cesar1125** [HuaweiSwitch/CloudEngine-Ansible#5]
Hi CloudEngine-Ansible Team

I am having some problems running playbooks with the **ce_command** module, I am able to run the documentation example:
 ansible -m ce_command -a "commands='display vlan summary' transport='cli' host=10.254.254.1 port=22 username=admin password=admin" localhost --connection local

But I am not  sure what is the correct syntax to include cli variable in my playbook:
```
vars:
  cli:
    host: 10.254.254.1
    username: admin
    password: admin
    transport: cli

- name: run display version on remote devices
  ce_command:
    commands: display version
    provider: "{{ cli }}"
```

**Comment by numone213** [comment]
hi, the playbook you wrote has some syntax error, I think the playbook should like this:
```
- name: test
  hosts: 10.135.182.157
  vars:
    cli:
      host: 10.135.182.157
      port: 12345
      username: rootDC
      password: Admin@123
      transport: cli

  tasks:

  - name: run display version on remote devices
    ce_command:
      commands: display version
      provider: "{{ cli }}"
```
I test this playbook ok.
