### ISSUE TITLE
ce_mtu fails with "Error: Interface does not exist."

### ISSUE THREAD

**Issue by kpostrup** [HuaweiSwitch/CloudEngine-Ansible#63]
When trying to configure interface mtu using `ce_mtu` it fails with the error:

```
Error: Interface does not exist.
```

I am using this configuration:
```
- name: "Configure jumbo frames and MTU on interface"
  ce_mtu:
    interface: 100GE1/0/1
    jumbo_max: 9216
    jumbo_min: 1518
    mtu: 9000
    provider: "{{ cli }}"
```
