### ISSUE TITLE
ce_bfd_global shows changes even though nothing has changed

### ISSUE THREAD

**Issue by kpostrup** [HuaweiSwitch/CloudEngine-Ansible#64]
I am trying to use the `ce_bfd_global` module, to enable bfd globally.
However, each time I run the playbook, ansible shows the task as having performed a change, even though nothing has changed on the switch (bfd was already enabled globally).

Here is the task:
```
- name: Enable BFD globally
  ce_bfd_global:
    bfd_enable: enable
    provider: '{{ cli }}'
```
Each time it is run, it shows:
```
TASK [common : Enable BFD globally] ******************************************************************************************************************************************
changed: [hostname]
```
