### ISSUE TITLE
Unsupported parameter "transport"

### ISSUE THREAD

**Issue by C-F-A** [HuaweiSwitch/CloudEngine-Ansible#81]
Hello,

When executing a playbook for any CE module, it fails with the message:
"Unsupported parameters for (ce_command) module: **transport** Supported parameters include: commands, interval, match, provider, retries, wait_for"

Example playbook:
```yaml
- name: test
  hosts: localhost
  connection: local
  vars:
    cli:
      host: 1.1.1.1
      port: 22
      username: "xxx"
      password: "xxx"

  tasks:
  - name: run display version on remote devices
    ce_command:
      commands: display version
      provider: "{{ cli }}"
```

Error message:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": "display version",
            "provider": {
                "host": "1.1.1.1",
                "password": "xxx",
                "port": 22,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "xxx",
                "validate_certs": null
            },
            "transport": "cli"
        }
    },
    "msg": "Unsupported parameters for (ce_command) module: transport Supported parameters include: commands, interval, match, provider, retries, wait_for"
}
```

Software versions:
Python 3.8.2
ansible 2.10.2
ncclient               0.6.9

Thanks in advance.

**Comment by baprx** [comment]
You should check the following page since this repo seems abandonned: https://docs.ansible.com/ansible/latest/network/user_guide/platform_ce.html

**Comment by ivan-1989** [comment]
I had same issue  and I have added in inventory 
 ansible_network_os: ce

And after that it is worked fine.

**Comment by C-F-A** [comment]
Thanks, that helped to get the on the right track.

I´ve now added to vars:
```
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: ce
    cli:
      host: "{{ host }}"
      port: "{{ port }}"
      username: "{{ user }}"
      password: "{{ pw }}"
```

Now I´m able to communicate to the switches, though login fails.
